### ISSUE TITLE
关于数据集开放的问题

### ISSUE THREAD

**Issue by hcmdgh** [DuanhaoranCC/RMR#1]
您好！感谢您提供的如此有价值的工作，请问您能否开放论文中所用的AMiner、DBLP、PubMed数据集呢？这种中、大规模的异构图数据集将对后续研究者的工作大有裨益，非常感谢您！（注：受限于GitHub仓库大小，您可考虑使用百度网盘、阿里网盘等。）

**Comment by DuanhaoranCC** [comment]
Thank you for your attention. We update Readme.
