### ISSUE TITLE
How to process DBLP dataset

### ISSUE THREAD

**Issue by hcmdgh** [DuanhaoranCC/RMR#2]
Hello! I notice that you have opened the DBLP dataset. But when I take a brief look at it, I find it has 12,609 venues for all papers. I wonder how do you process the dataset and build the target labels? Thanks a lot!

**Comment by DuanhaoranCC** [comment]
You're great, you can see PubMed way. Instead of choosing the full range of publication venues, we chose the top 100 or 200 with the highest number of publications as downstream task labels.

**Comment by hcmdgh** [comment]
Thanks a lot.
